/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "afeysknkwtjcgdseshur"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZXlza25rd3RqY2dkc2VzaHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MjUwNjIsImV4cCI6MjA3ODMwMTA2Mn0.dmd-EWjrLcTJdjbfga3SAe1KOKGRjTf_LS-seXNt5uw"